### ISSUE TITLE
pixel one or xl?

### ISSUE THREAD

**Issue by billpage911** [wacko1805/Pixel-spoof-props#2]
can we get a support for pixel one or xl ? ...for original quality

**Comment by wacko1805** [comment]
Heya,
I have already made an OG Pixel spoof in December. 
It has not been updated since then because Google discontinued updates for the device, so no updated fingerprints. 


[https://sourceforge.net/projects/pixel-spoof/files/OG%20Pixel%20Spoofs/](Download)

**Comment by billpage911** [comment]
but it's for android 11.... how do i change  it to work in android 10 ??

**Comment by wacko1805** [comment]
It works for both android 10 and 11.
